### ISSUE TITLE
Cant get it to display file from dropbox, local works though.

### ISSUE THREAD

**Issue by Sizer009** [eouia/MMM-HTMLBox#1]
I cant seem to get this to work with a file from dropbox, could you give an example of using an external file because I cant see an issue...

`{
  module: "MMM-HTMLBox",
  position:"top_center",
  header: "To-do List",
  config: {
    width: "400px",
    height: "200px",
    refresh_interval_sec:60,
    file: "http://www.dropbox.com/.....................Shopping.html", //When content is too long, you can use this for external file. rela$
  }
`

**Comment by eouia** [comment]
file would not be URL, it is local text or html file. You can use `iframe` tag for including external url.
